---
http_interactions:
- request:
    method: post
    uri: http://pld.com/api/v3/admin/product_lines.json
    body:
      encoding: UTF-8
      string: '{"product_line":{"name":"test product_line for deletion"}}'
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2JkYTBlMjFhMTc4ZjI5OGI3OWIzMTA5NDViMzI1OCIsImp0aSI6IjVhZjg3MDAwLTAxODMtMDEzZC00M2ZmLTJjZGU0ODAwMTEyMiIsImV4cCI6MTc0ODY5OTcyMH0.wACkSpBq3A9aXxfIkXJ-Syovv8JrPgG5Pa6qlAZLrqQ
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.25.3
      Date:
      - Mon, 03 Jun 2024 17:07:19 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Ratelimit-Limit:
      - '10'
      X-Ratelimit-Remaining:
      - '10'
      X-Ratelimit-Reset:
      - '1717434440'
      Cache-Control:
      - no-store
      Vary:
      - Origin
      Etag:
      - W/"63096b54a090dace94d4636e1e706e0c"
      X-Request-Id:
      - 1b063744-b228-41b1-96e3-90c43fd65d63
      X-Runtime:
      - '0.063264'
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
    body:
      encoding: UTF-8
      string: '{"id":4,"name":"test product_line for deletion","enabled_for_deals":true,"enabled_for_people":true,"enabled_for_companies":true}'
  recorded_at: Mon, 03 Jun 2024 17:07:19 GMT
- request:
    method: delete
    uri: http://pld.com/api/v3/admin/product_lines/4.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2JkYTBlMjFhMTc4ZjI5OGI3OWIzMTA5NDViMzI1OCIsImp0aSI6IjVhZjg3MDAwLTAxODMtMDEzZC00M2ZmLTJjZGU0ODAwMTEyMiIsImV4cCI6MTc0ODY5OTcyMH0.wACkSpBq3A9aXxfIkXJ-Syovv8JrPgG5Pa6qlAZLrqQ
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Server:
      - nginx/1.25.3
      Date:
      - Mon, 03 Jun 2024 17:07:19 GMT
      Connection:
      - keep-alive
      X-Ratelimit-Limit:
      - '10'
      X-Ratelimit-Remaining:
      - '10'
      X-Ratelimit-Reset:
      - '1717434440'
      Cache-Control:
      - no-store
      Vary:
      - Origin
      X-Request-Id:
      - 7e97f760-d480-4e6f-95d1-183c22965651
      X-Runtime:
      - '0.063572'
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Mon, 03 Jun 2024 17:07:19 GMT
- request:
    method: get
    uri: http://pld.com/api/v3/admin/product_lines.json?page=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2JkYTBlMjFhMTc4ZjI5OGI3OWIzMTA5NDViMzI1OCIsImp0aSI6IjVhZjg3MDAwLTAxODMtMDEzZC00M2ZmLTJjZGU0ODAwMTEyMiIsImV4cCI6MTc0ODY5OTcyMH0.wACkSpBq3A9aXxfIkXJ-Syovv8JrPgG5Pa6qlAZLrqQ
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.25.3
      Date:
      - Mon, 03 Jun 2024 17:07:19 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Ratelimit-Limit:
      - '10'
      X-Ratelimit-Remaining:
      - '10'
      X-Ratelimit-Reset:
      - '1717434440'
      Cache-Control:
      - no-store
      Vary:
      - Origin
      Etag:
      - W/"d801aa1fb7ddcc330a5e3173372ea6af"
      X-Request-Id:
      - 62ce1bac-bc37-4873-82c5-8fe852712383
      X-Runtime:
      - '0.031226'
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
    body:
      encoding: UTF-8
      string: '{"entries":[]}'
  recorded_at: Mon, 03 Jun 2024 17:07:19 GMT
recorded_with: VCR 6.1.0
