---
http_interactions:
- request:
    method: post
    uri: http://pld.com/api/v3/admin/product_lines.json
    body:
      encoding: UTF-8
      string: '{"product_line":{"name":"test product_line"}}'
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2JkYTBlMjFhMTc4ZjI5OGI3OWIzMTA5NDViMzI1OCIsImp0aSI6IjVhZjg3MDAwLTAxODMtMDEzZC00M2ZmLTJjZGU0ODAwMTEyMiIsImV4cCI6MTc0ODY5OTcyMH0.wACkSpBq3A9aXxfIkXJ-Syovv8JrPgG5Pa6qlAZLrqQ
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.25.3
      Date:
      - Mon, 03 Jun 2024 17:07:18 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Ratelimit-Limit:
      - '10'
      X-Ratelimit-Remaining:
      - '10'
      X-Ratelimit-Reset:
      - '1717434439'
      Cache-Control:
      - no-store
      Vary:
      - Origin
      Etag:
      - W/"484de7e19ac048bb42ea07cbeeb9c461"
      X-Request-Id:
      - 62721b26-d99f-4462-a739-f48a9686c954
      X-Runtime:
      - '0.078839'
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
    body:
      encoding: UTF-8
      string: '{"id":3,"name":"test product_line","enabled_for_deals":true,"enabled_for_people":true,"enabled_for_companies":true}'
  recorded_at: Mon, 03 Jun 2024 17:07:18 GMT
- request:
    method: delete
    uri: http://pld.com/api/v3/admin/product_lines/3.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2JkYTBlMjFhMTc4ZjI5OGI3OWIzMTA5NDViMzI1OCIsImp0aSI6IjVhZjg3MDAwLTAxODMtMDEzZC00M2ZmLTJjZGU0ODAwMTEyMiIsImV4cCI6MTc0ODY5OTcyMH0.wACkSpBq3A9aXxfIkXJ-Syovv8JrPgG5Pa6qlAZLrqQ
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Server:
      - nginx/1.25.3
      Date:
      - Mon, 03 Jun 2024 17:07:19 GMT
      Connection:
      - keep-alive
      X-Ratelimit-Limit:
      - '10'
      X-Ratelimit-Remaining:
      - '10'
      X-Ratelimit-Reset:
      - '1717434439'
      Cache-Control:
      - no-store
      Vary:
      - Origin
      X-Request-Id:
      - '09b01838-0184-4f51-bab6-6066253a329f'
      X-Runtime:
      - '0.116570'
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Mon, 03 Jun 2024 17:07:19 GMT
- request:
    method: get
    uri: http://pld.com/api/v3/admin/product_lines.json?page=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiM2JkYTBlMjFhMTc4ZjI5OGI3OWIzMTA5NDViMzI1OCIsImp0aSI6IjVhZjg3MDAwLTAxODMtMDEzZC00M2ZmLTJjZGU0ODAwMTEyMiIsImV4cCI6MTc0ODY5OTcyMH0.wACkSpBq3A9aXxfIkXJ-Syovv8JrPgG5Pa6qlAZLrqQ
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.25.3
      Date:
      - Mon, 03 Jun 2024 17:07:19 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Ratelimit-Limit:
      - '10'
      X-Ratelimit-Remaining:
      - '10'
      X-Ratelimit-Reset:
      - '1717434440'
      Cache-Control:
      - no-store
      Vary:
      - Origin
      Etag:
      - W/"d801aa1fb7ddcc330a5e3173372ea6af"
      X-Request-Id:
      - a6d7a296-6b4e-447e-9d00-4d032671f3b0
      X-Runtime:
      - '0.030709'
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
    body:
      encoding: UTF-8
      string: '{"entries":[]}'
  recorded_at: Mon, 03 Jun 2024 17:07:19 GMT
recorded_with: VCR 6.1.0
